# Generated by Django 6.0.4 on 2026-05-04 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_chunks', models.IntegerField()),
                ('received_chunks', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('temp_dir', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chunk_uploads',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('version_number', models.IntegerField(default=1)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('parent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='files.file')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='folders_owner_i_88f787_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'is_deleted'], name='files_owner_i_42e4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash'], name='files_file_ha_3fed72_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'folder'], name='files_owner_i_07b91f_idx'),
        ),
    ]
