# Generated by Django 6.0.4 on 2026-05-08 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='groups.group'),
        ),
        migrations.AddField(
            model_name='folder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['group', 'is_deleted'], name='files_group_i_dd29d4_idx'),
        ),
    ]
