# Generated by Django 6.0.4 on 2026-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_group_fk'),
        ('files', '0002_file_add_ipgroup_fields'),
    ]

    operations = [
    ]
